# Generated by Django 6.0.3 on 2026-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=10)),
                ('platform', models.CharField(default='LeetCode', max_length=100)),
                ('date_solved', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
