# Generated by Django 6.0.3 on 2026-04-04 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-date_solved', '-created_at'], 'verbose_name_plural': 'Problems'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='attempts',
            field=models.PositiveIntegerField(default=1, help_text='Number of attempts before success'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='date_solved',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date this problem was completed'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark for quick access or later review'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='notes',
            field=models.TextField(blank=True, help_text='Document your approach or tricky edge cases'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='platform',
            field=models.CharField(default='LeetCode', help_text='Platform where the problem was solved', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_url',
            field=models.URLField(blank=True, help_text='Direct link to the problem statement', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select relevant algorithm/DS categories', to='tracker.tag'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_taken',
            field=models.PositiveIntegerField(blank=True, help_text='Total minutes taken to solve', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(help_text='The exact title of the problem', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='leetcode_username',
            field=models.CharField(help_text='Your public LeetCode handle', max_length=100, unique=True),
        ),
    ]
